### ISSUE TITLE
Issue on macOS Big Sur (and temporary workaround / patch version)

### ISSUE THREAD

**Issue by liamdon** [BlenderNPR/BEER#19]
On macOS Big Sur, the addon is not able to locate the OpenGL Framework. This may be due to [an issue in cpython](https://github.com/python/cpython/pull/21241), which has now been patched - maybe updating the dependency would fix it?

In the meantime, I was able to patch the problem and get it working using [this method](https://stackoverflow.com/a/64021312). 

For the convenience of anyone reading, [here is a patched version of BEER for macOS Big Sur](https://www.dropbox.com/s/jlluhytb3kwdz15/BlenderMalt-macOS-OpenGLPatch.zip?dl=0). Note that this is the release version, not latest master.

**Comment by pragma37** [comment]
Hi! Thanks for taking the time to figure out the problem before opening the issue.

Looks like the VFX reference platform will stick to python 3.7 for 2021 so it could take a while before Blender gets the cpython fix.

I've implemented a way to patch dependencies at build time and implemented the fix from this issue:
https://github.com/mcfletch/pyopengl/issues/55

Could you try the latest release and check if it works for you?

**Comment by liamdon** [comment]
Thanks for getting back to me! I think this did not fix it. The error message looks different from the one I remember though, here is the new one:

```
Traceback (most recent call last):
  File "/Users/liam/Library/Application Support/Blender/2.91/scripts/addons/BlenderMalt/__init__.py", line 24, in <module>
    import OpenGL, OpenGL_accelerate, pcpp, pyrr
ModuleNotFoundError: No module named 'OpenGL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liam/Library/Application Support/Blender/2.91/scripts/addons/BlenderMalt/__init__.py", line 31, in <module>
    install_dependencies()
  File "/Users/liam/Library/Application Support/Blender/2.91/scripts/addons/BlenderMalt/__init__.py", line 29, in install_dependencies
    subprocess.check_call([bpy.app.binary_path_python, '-m', 'pip', 'install', *dependencies, '--target', malt_dependencies_path])
  File "/Applications/Blender.app/Contents/Resources/2.91/python/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Applications/Blender.app/Contents/Resources/2.91/python/bin/python3.7m', '-m', 'pip', 'install', 'PyOpenGL', 'PyOpenGL_accelerate', 'pcpp', 'Pyrr', '--target', '/Users/liam/Library/Application Support/Blender/2.91/scripts/addons/BlenderMalt/MaltDependencies']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.91/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/liam/Library/Application Support/Blender/2.91/scripts/addons/BlenderMalt/__init__.py", line 36, in <module>
    install_dependencies()
  File "/Users/liam/Library/Application Support/Blender/2.91/scripts/addons/BlenderMalt/__init__.py", line 29, in install_dependencies
    subprocess.check_call([bpy.app.binary_path_python, '-m', 'pip', 'install', *dependencies, '--target', malt_dependencies_path])
  File "/Applications/Blender.app/Contents/Resources/2.91/python/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Applications/Blender.app/Contents/Resources/2.91/python/bin/python3.7m', '-m', 'pip', 'install', 'PyOpenGL', 'PyOpenGL_accelerate', 'pcpp', 'Pyrr', '--target', '/Users/liam/Library/Application Support/Blender/2.91/scripts/addons/BlenderMalt/MaltDependencies']' returned non-zero exit status 1.

```

**Comment by liamdon** [comment]
Correction - it did work, I think I forgot to restart Blender between removing the old version and installing/enabling the new version.

**Comment by pragma37** [comment]
Great! Closing this.
