### ISSUE TITLE
Nothing is rendered, viewport all gray

### ISSUE THREAD

**Issue by vidur501** [BlenderNPR/BEER#328]
### Malt version

Release / "blender-3.1-last-version Pre-release"

### Blender version

Blender 3.1.2

### OS

manjaro stable x64

### Hardware info

intel i7-4790K | 16GB RAM | Radeon HD7750

### Issue description and reproduction steps

Starting with a fresh file, malt works, but if I try to use it in an existing project, the viewport is just gray and the render is transparent.

error messages:
when switching to Malt

```
Python: Traceback (most recent call last):
  File "/home/vidur/.config/blender/3.1/scripts/addons/BlenderMalt/MaltRenderEngine.py", line 215, in update_render_passes
    bridge = MaltPipeline.get_bridge(scene.world, True)
  File "/home/vidur/.config/blender/3.1/scripts/addons/BlenderMalt/MaltPipeline.py", line 27, in get_bridge
    world.malt.update_pipeline(bpy.context)
  File "/home/vidur/.config/blender/3.1/scripts/addons/BlenderMalt/MaltPipeline.py", line 93, in update_pipeline
    setup_all_ids()
  File "/home/vidur/.config/blender/3.1/scripts/addons/BlenderMalt/MaltPipeline.py", line 170, in setup_all_ids
    setup_parameters(bpy.data.meshes)
  File "/home/vidur/.config/blender/3.1/scripts/addons/BlenderMalt/MaltPipeline.py", line 203, in setup_parameters
    bid.malt_parameters.setup(parameters)
  File "/home/vidur/.config/blender/3.1/scripts/addons/BlenderMalt/MaltProperties.py", line 226, in setup
    setup_parameter(name, parameter)
  File "/home/vidur/.config/blender/3.1/scripts/addons/BlenderMalt/MaltProperties.py", line 125, in setup_parameter
    self.bools.add().name = name
TypeError: bpy_prop_collection.add(): not supported for this collection

location: <unknown location>:-1
```

when switching to rendered viewport

```
Python: Traceback (most recent call last):
  File "/home/vidur/.config/blender/3.1/scripts/addons/BlenderMalt/MaltRenderEngine.py", line 305, in view_draw
    scene = self.get_scene(context, depsgraph, self.request_scene_update, overrides)
  File "/home/vidur/.config/blender/3.1/scripts/addons/BlenderMalt/MaltRenderEngine.py", line 191, in get_scene
    add_object(obj, obj.matrix_world, id)
  File "/home/vidur/.config/blender/3.1/scripts/addons/BlenderMalt/MaltRenderEngine.py", line 110, in add_object
    malt_mesh = MaltMeshes.get_mesh(obj)
  File "/home/vidur/.config/blender/3.1/scripts/addons/BlenderMalt/MaltMeshes.py", line 15, in get_mesh
    MESHES[key] = load_mesh(object, key)
  File "/home/vidur/.config/blender/3.1/scripts/addons/BlenderMalt/MaltMeshes.py", line 62, in load_mesh
    if i == 0 and object.original.data.malt_parameters.bools['precomputed_tangents'].boolean:
KeyError: 'bpy_prop_collection[key]: key "precomputed_tangents" not found'

location: <unknown location>:-1
```

### Attachments

[malt 2022-06-13(10-00).log](https://github.com/bnpr/Malt/files/8889488/malt.2022-06-13.10-00.log)

**Comment by pragma37** [comment]
Seems related to this? https://developer.blender.org/T82118

I've made all the BlenderMalt properties library editable 5868662c0e9299baac5b89c724b55d5fd2acec4d (not sure why this is not the default).

Could you check if that fixes your issue? 
https://github.com/bnpr/Malt/releases/tag/Development-latest
(You'll need Blender 3.2)

**Comment by vidur501** [comment]
Sorry, I can't check in 3.2 since BlenderMalt-Linux Development-latest of 10.6.2022 can't be activated:

```
Traceback (most recent call last):
  File "/home/vidur/blender-3.2.0-linux-x64/3.2/scripts/modules/addon_utils.py", line 371, in enable
    mod.register()
  File "/home/vidur/.config/blender/3.2/scripts/addons/BlenderMalt/__init__.py", line 200, in register
    Bridge.reload()
  File "/home/vidur/.config/blender/3.2/scripts/addons/BlenderMalt/.MaltPath/Bridge/__init__.py", line 3, in reload
    from . import Client_API, Server, Material, Mesh, Texture
  File "/home/vidur/.config/blender/3.2/scripts/addons/BlenderMalt/.MaltPath/Bridge/Server.py", line 6, in <module>
    import glfw
  File "/home/vidur/.config/blender/3.2/scripts/addons/BlenderMalt/.MaltPath/Malt/.Dependencies-310/glfw/__init__.py", line 43, in <module>
    raise ImportError("Failed to load GLFW3 shared library.")
ImportError: Failed to load GLFW3 shared library.
```
or is there an older version for 3.2 that works?

**Comment by pragma37** [comment]
That's weird.
The [blender-3.1-last-version](https://github.com/bnpr/Malt/releases/tag/blender-3.1-last-version) and the [Development-latest](https://github.com/bnpr/Malt/releases/tag/Development-latest) releases are using the exact same glfw version.

Sorry, but I have no idea why it would fail to load. It's likely a "Linux being Linux" thing.

**Comment by vidur501** [comment]
Guess I have an idea: 3.2 was just extracted from a zip file, but 3.1.2 is installed from the manjaro repositories.
On a different machine, I upgraded manjaro to the latest version which includes blender 3.2. There, the addon can be activated in blender 3.2 from the repos and it can't be activated in 3.2 extracted from a zip file.
Could this be an issue with the path to the library?

**Comment by pragma37** [comment]
I guess the repository Blender version could be loading a Manjaro specific GLFW built-in version or something along those lines.

You could try to delete the library that ships with Malt and see if that helps.
`/home/vidur/.config/blender/3.2/scripts/addons/BlenderMalt/.MaltPath/Malt/.Dependencies-310/glfw` in the x11 and wayland folders.

Have you tested the broken file in the other machine? Does it work now?

**Comment by vidur501** [comment]
After renaming both glfw files, I still get "ImportError: Failed to load GLFW3 shared library." 
The only glfw I found installed is glfw-x11 3.3.7-1

Unfortunately, the scene is also gray/renders transparent in Blender 3.2. Errors:
- Type Error: bpy_prop_collection.add(): not supported for this collection
- KeyError: 'key not in subgroup dict'

So Malt does not work if it can't add properties to collections?

**Comment by pragma37** [comment]
The error is supposedly related to linked library overrides, but I'm unable to reproduce it myself, even in the version previous to the patch.

If you can provide a file (files I guess) to reproduce the issue I could take a better look.

**Comment by vidur501** [comment]
Here are the files - I managed to get the issue in "Malt Bug - Link to.blend"
[Malt Bug.zip](https://github.com/bnpr/Malt/files/8894036/Malt.Bug.zip)
Adding an instance of "linked collection 1" to Collection 3 in Scene A did the trick and once it is there, deleting it does not remove the rendering issue.
Still I'm not exactly sure what in these files is necessary to trigger the issue and what is not.
Please note that Blender's outliner has no way of showing if a collection is linked to multiple scenes or not.

**Comment by pragma37** [comment]
By default the scene is full black because you replaced the Background Material with a Mesh Material:
![imagen](https://user-images.githubusercontent.com/36610999/173445235-5d3fc271-54f8-4b16-b522-a05f8c071d1c.png)

Here I'm simply bypassing the screen pass:
![imagen](https://user-images.githubusercontent.com/36610999/173445534-600b6d23-1d08-43a9-80bf-b39f86920f59.png)

With a sun light:
![imagen](https://user-images.githubusercontent.com/36610999/173445892-613749c0-5a1c-4da1-9ff7-555ddfe08118.png)

[link_override.zip](https://github.com/bnpr/Malt/files/8894493/link_override.zip)

**Comment by vidur501** [comment]
So after you open the "link to" file and switch to rendered viewport does it look like this?
![render](https://user-images.githubusercontent.com/100998713/173459580-3dc4c599-19cf-49ca-b169-e122589c0492.jpg)
and like this if you do a render?
![viewport render](https://user-images.githubusercontent.com/100998713/173459583-e1530a3c-1866-4ab3-854c-248a875b5696.jpg)


You are right, bypassing the pass helps in this case, but then it seems like the file is not reproducing my issue, because
- there are no such error messages like I posted earlier
- "Malt - Default Mesh Material" always was the default in World, I did not change this (and it never was a problem).
- if I change the world background of my actual project file (that I can't upload) to "Malt - Background Material", it does not solve the issue.

So I have to try again to reproduce the real issue.

**Comment by zNightlord** [comment]
I have the same issue
but for 3.2 this happen everything rendered as gray like that the background shader is replaced with the mesh shader when you change it, it prompt `Wrong shader extension, should be .mesh glsl` 
![image](https://user-images.githubusercontent.com/61040487/177089496-a54b1e44-4e2a-42fb-b21d-e8d10129a770.png)
I tried the example material file it happen the same work in 3.1 but not in 3.2.

**Comment by pragma37** [comment]
> the background shader is replaced with the mesh shader

Do you mean it happened on its own? 🤔
Can you change it back to the Default Mesh Material?

**Comment by vidur501** [comment]
The issue is solved in BlenderMalt-Linux Development-latest (85289f4 of 24.6.2022) and the errors
  ```
  TypeError: bpy_prop_collection.add(): not supported for this collection
  KeyError: 'bpy_prop_collection[key]: key "precomputed_tangents" not found'
```
are gone.

I checked with BlenderMalt-Linux Development-latest of 10.6.2022: everything is still gray there, so the issue was solved by malt itself (not by my updated drivers).

[zNightlord](https://github.com/zNightlord) can you try this version?

**Comment by zNightlord** [comment]
It's still the same for me now except the changing thing with the current version.
maybe it's better for me to create a new issue then.

**Comment by pragma37** [comment]
@vidur501 Nice. Thanks for reporting.

It would be great to know what fixed it, but whatever. 🤷
