### ISSUE TITLE
Very Laggy and Unresponsive

### ISSUE THREAD

**Issue by AhsanSarwar45** [BlenderNPR/BEER#33]
As soon I enable the addon, the interface starts lagging, even though I have not changed the renderer to Malt yet. There is a solid one second of lag when clicking anything (The viewport, including the buttons, is completely smooth though). After changing the renderer to Malt, things stay exactly the same. But when I load a shader file into the Shader Source in the materials tab, the lag kicks into sixth gear, making everything pretty much unusable. I also noticed that the 'Malt Properties' was not displaying any properties:

![image](https://user-images.githubusercontent.com/41967492/103139666-4188f980-4700-11eb-85c5-51ac3050303c.png)

Also, my test cube turns completely gray (In both material and renderer view):

![image](https://user-images.githubusercontent.com/41967492/103139687-83b23b00-4700-11eb-8826-7ce128c2de74.png)

My graphic drivers are updated but my integrated graphic card is pretty old, which I suspect is the problem.

Specs:
Laptop: Lenovo B50-80
CPU: Intel Core i5-5200U
Video Card: Intel HD Graphics 5500
OS: Windows 10 Version 10.0.18363 Build 18363
DirectX version: 11.4
OpenGL version: 4.4

Blender Version 2.91.0 (Also tried on 2.90 and got exactly the same issues)

Eevee and Cycles work completely fine.

Here is the stack trace:

When I install and enable the addon and close the preferences window:

```
Writing userprefs: 'C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\config\userpref.blend' ok
Traceback (most recent call last):
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPipeline.py", line 110, in depsgraph_update
    setup_all_ids()
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPipeline.py", line 93, in setup_all_ids
    setup_parameters(bpy.data.scenes)
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPipeline.py", line 71, in setup_parameters
    pipeline_parameters = get_pipeline().get_parameters()
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPipeline.py", line 22, in get_pipeline
    bpy.context.scene.world.malt.update_pipeline(bpy.context)
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPipeline.py", line 40, in update_pipeline
    __PIPELINE__ = _cls()
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPath\Malt\Pipelines\NPR_Pipeline\NPR_Pipeline.py", line 43, in __init__
    super().__init__()
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPath\Malt\Pipeline.py", line 52, in __init__
    self.quad = Mesh(positions, indices)
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPath\Malt\GL\Mesh.py", line 24, in __init__
    glGenBuffers(1, self.EBO)
  File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 311, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltDependencies\OpenGL\platform\baseplatform.py", line 425, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glGenBuffers, check for bool(glGenBuffers) before calling
```

Whenever I click anywhere except the viewport buttons:

```
Traceback (most recent call last):
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPipeline.py", line 110, in depsgraph_update
    setup_all_ids()
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPipeline.py", line 93, in setup_all_ids
    setup_parameters(bpy.data.scenes)
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPipeline.py", line 71, in setup_parameters
    pipeline_parameters = get_pipeline().get_parameters()
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPipeline.py", line 22, in get_pipeline
    bpy.context.scene.world.malt.update_pipeline(bpy.context)
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPipeline.py", line 40, in update_pipeline
    __PIPELINE__ = _cls()
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPath\Malt\Pipelines\NPR_Pipeline\NPR_Pipeline.py", line 61, in __init__
    if _DEFAULT_SHADER is None: _DEFAULT_SHADER = self.compile_material_from_source('mesh', _DEFAULT_SHADER_SRC)
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPath\Malt\Pipelines\NPR_Pipeline\NPR_Pipeline.py", line 81, in compile_material_from_source
    source, include_paths, ['IS_MESH_SHADER','PRE_PASS']
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPath\Malt\Pipeline.py", line 219, in compile_shader_from_source
    return Shader(vertex, pixel)
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPath\Malt\GL\Shader.py", line 31, in __init__
    self.uniforms = reflect_program_uniforms(self.program)
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPath\Malt\GL\Shader.py", line 263, in reflect_program_uniforms
    gl_get[base_type](program, location, value)
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1285,
        description = b'out of memory',
        baseOperation = glGetUniformiv,
        cArguments = (
                265,
                3272,
                <Malt.GL.GL.c_ubyte_Array_1 object at 0x000001DFAF887448>,
        )
)
```
After I load in the shader file, this traceback keeps getting called:
```
Traceback (most recent call last):
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltMaterial.py", line 209, in track_shader_changes
    material.malt.update_source(bpy.context)
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltMaterial.py", line 39, in update_source
    compiled_material = MaltPipeline.get_pipeline().compile_material(path)
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPipeline.py", line 22, in get_pipeline
    bpy.context.scene.world.malt.update_pipeline(bpy.context)
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPipeline.py", line 40, in update_pipeline
    __PIPELINE__ = _cls()
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPath\Malt\Pipelines\NPR_Pipeline\NPR_Pipeline.py", line 61, in __init__
    if _DEFAULT_SHADER is None: _DEFAULT_SHADER = self.compile_material_from_source('mesh', _DEFAULT_SHADER_SRC)
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPath\Malt\Pipelines\NPR_Pipeline\NPR_Pipeline.py", line 81, in compile_material_from_source
    source, include_paths, ['IS_MESH_SHADER','PRE_PASS']
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPath\Malt\Pipeline.py", line 219, in compile_shader_from_source
    return Shader(vertex, pixel)
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPath\Malt\GL\Shader.py", line 31, in __init__
    self.uniforms = reflect_program_uniforms(self.program)
  File "C:\Users\Ahsan Sarwar\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlenderMalt\MaltPath\Malt\GL\Shader.py", line 263, in reflect_program_uniforms
    gl_get[base_type](program, location, value)
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1285,
        description = b'out of memory',
        baseOperation = glGetUniformiv,
        cArguments = (
                475,
                3272,
                <Malt.GL.GL.c_ubyte_Array_1 object at 0x000001DFAF80D148>,
        )
)
```

**Comment by pragma37** [comment]
Hi. There are 2 problems here.

1. Blender doesn't seem to have a valid OpenGL context active.
2. Malt tries to setup itself but it fails since there's no OpenGL context, so it tries again and again.

Number 2 should be fixed in 6d69ec04049e2d054f0dce9206ae378b8c09c27b, so hopefully you shouldn't have more performance issues.

Number 1 is trickier since it's related to Blender itself and (likely) Intel OpenGL drivers, which has been the nº 1 cause of bug reports so far.
Does Malt viewport rendering work for you ?

**Comment by AhsanSarwar45** [comment]
It works when viewport rendering in solid/wireframe/matcap mode but in rendering/material mode, I get the grayed out cube like in the image in my original post.

**Comment by AhsanSarwar45** [comment]
Also, I am using the latest release but I still get the performance issues when clicking and after adding a shader source file.

**Comment by pragma37** [comment]
After reading your console logs again, looks like your graphics card don't have enough memory to run Malt.

Sorry, but there's not too much I can do about that.
