### ISSUE TITLE
Shader compilation errors on Node-UX-Latest

### ISSUE THREAD

**Issue by noctiswhole** [BlenderNPR/BEER#387]
### Malt version

node-ux-latest

### Blender version

Blender 3.2.1

### OS

Pop!_OS 22.04

### Hardware info

AMD Ryzen 2600X | 32GB RAM | NVIDIA GeForce RTX 3080 10GB

### Issue description and reproduction steps

Uninstalled previous malt version, installed node-ux-latest. Getting shader compiler errors on a brand new default project (default cube, etc) with a viewport render. Did nothing other than switch viewport render and switch to the Malt renderer.

![image](https://user-images.githubusercontent.com/101479200/187045545-b838ef8c-c778-4353-b7b6-b83d64565c8c.png)

### Attachments

[system-info.txt](https://github.com/bnpr/Malt/files/9438569/system-info.txt)
[malt 2022-08-27(14-26).log](https://github.com/bnpr/Malt/files/9438570/malt.2022-08-27.14-26.log)

**Comment by pragma37** [comment]
We got the exact same issue reported here: https://github.com/bnpr/Malt/issues/384#issuecomment-1223478394
It seemingly got solved by itself.
  
Seems like the source code generation step of one node is skipped, but I have no idea how that could happen.
Does the Blender terminal print any other error?
What happens if you save the file?
What happens if you edit the Background Node Tree?

**Comment by pragma37** [comment]
I guess this version has the same error?
https://github.com/bnpr/Malt/releases/tag/node-tree-properties-latest

**Comment by noctiswhole** [comment]
> I guess this version has the same error?

I get a similar error for the same shader with a dfiferent variable undefined:

```SHADER COMPILER ERROR :
/home/noctiswhole/Projects/minnie/.malt-autogenerated/test-Background Node Tree.screen.glsl(28) : error C1503: undefined variable "__0_result"
```

> Does the Blender terminal print any other error?

I don't see any other errors other than the undefined variable errors.

> What happens if you save the file?

Saving the file does not fix the error.

> What happens if you edit the Background Node Tree?

Editing the background node tree throws a similar shader compiler error with undefined variable:

```SHADER COMPILER ERROR :
/home/noctiswhole/Projects/minnie/.malt-autogenerated/test-Background Node Tree.screen.glsl(28) : error C1503: undefined variable "_Layer_Blend1_0_result"
SHADER LINKER ERROR :
Vertex info
-----------
/home/noctiswhole/.config/blender/3.2/scripts/addons/BlenderMalt/.MaltPath/Malt/Shaders/Common.glsl(18) : warning C7050: "MODEL[0]" might be used before being initialized
/home/noctiswhole/.config/blender/3.2/scripts/addons/BlenderMalt/.MaltPath/Malt/Shaders/Common.glsl(18) : warning C7050: "MODEL[1]" might be used before being initialized
/home/noctiswhole/.config/blender/3.2/scripts/addons/BlenderMalt/.MaltPath/Malt/Shaders/Common.glsl(18) : warning C7050: "MODEL[2]" might be used before being initialized
/home/noctiswhole/.config/blender/3.2/scripts/addons/BlenderMalt/.MaltPath/Malt/Shaders/Common.glsl(18) : warning C7050: "MODEL[3]" might be used before being initialized

Fragment info
-------------
/home/noctiswhole/Projects/minnie/.malt-autogenerated/test-Background Node Tree.screen.glsl(28) : error C1503: undefined variable "_Layer_Blend1_0_result"
(0) : error C2003: incompatible options for link```

**Comment by noctiswhole** [comment]
Playing around with it more It's complaining about variables that start with double underscores being reserved:

[malt-errors.log](https://github.com/bnpr/Malt/files/9439163/malt-errors.log)

I don't know if it's related but trying to add my own `SCREEN SHADER` input and output nodes seems borked:
![image](https://user-images.githubusercontent.com/101479200/187059711-3ac99759-bdcb-415e-ad56-405ee5ec145f.png)

**Comment by pragma37** [comment]
If you have multiple Output nodes of the same type, only one will be used (It's currently not possible to select which one).
But in my case, it doesn't cause any compiler errors.


I'm really clueless about what could be going on.

I've made a custom version of the MaltNodeTree.py file that prints extra info while compiling node trees.
[MaltNodeTree.zip](https://github.com/bnpr/Malt/files/9439987/MaltNodeTree.zip)
Could you extract it into ` /home/noctiswhole/.config/blender/3.2/scripts/addons/BlenderMalt/MaltNodes/`, run Blender and copy the terminal content here?

Hopefully, that should help me to narrow down the issue.

**Comment by pragma37** [comment]
I just managed to reproduce this issue by upgrading from Ubuntu 20.04 to 22.04.

So, "good" news I guess. XD

Edit: Not anymore.😕

**Comment by Kolupsy** [comment]
Getting similar issues on a 'new' / different machine on Windows 10. The `node-ux` branch works well but the issues happen on the `node-tree-properties` branch. I was able to 'fix' them by reloading the pipeline but they cause Malt not to register properly in when starting up.

![image](https://user-images.githubusercontent.com/88381426/187207793-408a2c27-8952-4229-b1c6-e9f0e6683f4f.png)

**Comment by pragma37** [comment]
@Kolupsy This could be related, but I wouldn't take it as a given.
Seems like the issue there is that the MaltNode.internal_name is not set at source generation time.

I was able to consistently reproduce the original issue on a clean Ubuntu install.  
For whatever reason, `isinstance(node, MaltNode)` returns false on some Malt nodes.  
I've had similar issues before with `isinstance` when the import path doesn't match, but it's quite weird that it happens only on some machines.

I'll replace the `isinstance` calls with a different check. I hope that fixes the issues. 🤞

**Comment by Kolupsy** [comment]
may be useful to look at the protocol design pattern in this case (dont know the exact details of the problem to be solved but if the check is to ensure that the object has certain methods for malt to use then it might be a good alternative as it doenst care about interhitence)

**Comment by pragma37** [comment]
I can't test it at the Ubuntu machine at the moment, but I think the issue should be fixed in the node-ux branch now.

@Kolupsy Yep, I've basically removed all isinstance checks for custom types with hasattr calls and bl_idname or .__class__.__name__ checks.

**Comment by noctiswhole** [comment]
Thanks, I'll try it out eefa3768faadac72f62a2a87efbbc728b4e89df8 to see if it fixes my issues when I can.

**Comment by CG-GeisT** [comment]
I'm not sure if this is related or if I should open a new issue, but I finally had some time to mess around with malt again.
I ran into another problem where none of the vec3 shaders (like NPR and Diffuse) displays as black when plugged into a vec4 socket. The website says that Malt has automatic type conversion, so it shouldn't be an issue. Strangely, Malt doesn't throw an error this time.

![image](https://user-images.githubusercontent.com/68447848/187330289-f7f0e625-b8c4-43de-9c68-aaa09358808e.png)

It does display color with other vec4 outputs

![image](https://user-images.githubusercontent.com/68447848/187330859-a8662331-7d48-44e0-83a2-5c6681f55f16.png)

**Comment by noctiswhole** [comment]
The change got rid of the shader errors, but I also get just black output for the NPR vec3 nodes like above.

**Comment by Kolupsy** [comment]
The NPR Diffuse node shows just black when there are not any lights in your scene. Could this be the case?

Edit: could also be when your lights are too far away or not pointing at your object (for point and spot lights)

**Comment by CG-GeisT** [comment]
> Edit: could also be when your lights are too far away or not pointing at your object (for point and spot lights)

Yep, that was it
![image](https://user-images.githubusercontent.com/68447848/187444457-78035b1b-e48f-4bff-ad47-681e332de8e1.png)
Thank you!

**Comment by pragma37** [comment]
Closing this, then. 👍
